{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
    rules:
      - host: {{ .Values.ingress.hostname }}
        http:
          paths:
            - path: {{ .Values.ingress.path }}
              backend:
                serviceName: {{ include "chart.fullname" . }}
                servicePort: {{ .Values.service.externalport }}
{{- end -}}
